Repository Qiskit/qiskit-metapackage, pull requests merged in 2019-11, with the labels that each got.

#662 Change documentation theme to Read the Docs
  docs/conf.py
  docs/theme/_templates/drawer.html
  docs/theme/_templates/globaltoc.html
  docs/theme/_templates/layout.html
  docs/theme/_templates/relations.html
  docs/theme/_templates/search.html
  docs/theme/layout.html
  docs/theme/static/css/theme-override.css
  docs/theme/static/css/theme.css
  docs/theme/static/js/themeExt.js
  docs/theme/versions.html
  docs/versionutils.py
  requirements-dev.txt
  tools/deploy_documentation.sh
  tox.ini
Labels: theme

#661 Refactor master clone logic and set content_prefix to poBranch
  tools/deploy_documentation.sh
Labels: theme

#624 Update LOCALIZATION_CONTRIBUTORS
  docs/LOCALIZATION_CONTRIBUTORS
Labels: Localization

#683 Use IBM Plex in headers and other elements
  docs/theme/static/css/theme-override.css
Labels: documentation, theme

#693 Set logo-only to False
  docs/conf.py
Labels: documentation

#703 Proofread contributions guidelines
  docs/contributing_to_qiskit.rst
Labels: documentation

#702 Fix lowest error
  docs/errors/errors.rst
Labels: bug, documentation

#708 Explain Qiskit support of Python versions
  docs/install.rst
Labels: documentation
