Repository Qiskit/qiskit-metapackage, pull requests merged in 2019-08, with the labels that each got.

#403 Standardizing documentation for easier and better translation
  docs/aer/device_noise_simulation.rst
  docs/aer/index.rst
  docs/aer/simulate_experiments.rst
  docs/aer/simulate_statevectors.rst
  docs/aer/simulate_unitary_matrix.rst
  docs/aqua/CONTRIBUTORS.rst
  docs/aqua/ai/qiskit_ai.rst
  docs/aqua/chemistry/qiskit_chemistry.rst
  docs/aqua/circuit_collection.rst
  docs/aqua/index.rst
  docs/aqua/installation.rst
  docs/aqua/library.rst
  docs/aqua/multiclass_extensions.rst
  docs/getting_started.rst
  docs/ignis/index.rst
  docs/index.rst
  docs/release_notes.rst
  docs/terra/backend_monitoring_tools.rst
  docs/terra/index.rst
  docs/terra/terra_parallel_tools.rst
  docs/terra/transpiler/about/api.rst
  docs/terra/transpiler/about/index.rst
  docs/terra/transpiler/about/pass_managers.rst
  docs/terra/transpiler/about/passes.rst
  docs/terra/transpiler/getting_started.rst
  docs/terra/transpiler/index.rst
  docs/terra/user_config.rst
  docs/terra/visualizing_a_quantum_circuit.rst
Labels: documentation

#455 Cleanup old referencing labels from docs
  docs/getting_started.rst
  docs/release_notes.rst
Labels: WIP

#469 Need to add Ignis API
  docs/apidoc/ignis/characterization/characterization.rst
  docs/apidoc/ignis/ignis.rst
  docs/apidoc/ignis/mitigation/measurement/measurement.rst
  docs/apidoc/ignis/mitigation/mitigation.rst
  docs/apidoc/ignis/verification/randomized_benchmarking/randomized_benchmarking.rst
  docs/apidoc/ignis/verification/tomography/tomography.rst
  docs/apidoc/ignis/verification/verification.rst
  docs/apidoc/qiskit.rst
Labels: documentation

#473 Updating missing apidocs in Ignis
  Makefile
  docs/apidoc/ignis/characterization/characterization.rst
  docs/apidoc/ignis/characterization/coherence/coherence.rst
  docs/apidoc/ignis/characterization/gates/gates.rst
  docs/apidoc/ignis/characterization/hamiltonian/hamiltonian
  docs/apidoc/ignis/verification/quantum_volume/quantum_volume.rst
  docs/apidoc/ignis/verification/verification.rst
Labels: documentation

#478 Fixing layouts for localization
  docs/conf.py
  docs/theme/_templates/globaltoc.html
  docs/theme/_templates/layout.html
  docs/theme/static/css/theme.css
Labels: Localization, documentation

#489 Enable Localization automation
  .travis.yml
  tools/deploy_documentation.sh
Labels: Localization, documentation

#495 Make issue template relevant to API style docs
  .github/ISSUE_TEMPLATE/documentation.md
Labels: documentation

#494 Create LOCALIZATION_CONTRIBUTORS
  docs/LOCALIZATION_CONTRIBUTORS
Labels: documentation

#513 Clone source files in master branch to generate updated html
  tools/deploy_documentation.sh
Labels: Localization

#514 Revert "Remove toggle button (#498)"
  docs/theme/_templates/globaltoc.html
Labels: Localization

#515 Broken links in the_elements.rst
  docs/the_elements.rst
Labels: documentation

#519 Ignore LOCALIZATION_CONTRIBUTORS from authors file
  tools/generate_authors.py
Labels: documentation

#521 Update LOCALIZATION_CONTRIBUTORS
  docs/LOCALIZATION_CONTRIBUTORS
Labels: Localization

#522 Typo in the_elements.rst
  docs/the_elements.rst
Labels: documentation

#516 Explain how to contribute to doc localization
  docs/contributing_to_qiskit.rst
Labels: Localization, documentation

#518 Fix link typo in the_elements.rst
  docs/the_elements.rst
Labels: documentation

#523 Add a README to docs/
  docs/README.md
Labels: documentation
