Repository Qiskit/qiskit-metapackage, pull requests merged in 2019-05, with the labels that each got.

#207 Update Install from Source instructions for Qiskit Terra
  docs/contributing_to_qiskit.rst
  docs/index.rst
  docs/install.rst
Labels: documentation

#219 add FAQ
  docs/faq.rst
  docs/index.rst
Labels: documentation

#224 order of elements to install from source
  docs/contributing_to_qiskit.rst
Labels: documentation

#225 Add alt-text to all images in Qiskit docs
  docs/aer/device_noise_simulation.rst
  docs/getting_started.rst
  docs/ignis/overview.rst
  docs/terra/plotting_data_in_qiskit.rst
  docs/terra/quantum_circuits.rst
  docs/terra/visualizing_a_quantum_circuit.rst
Labels: documentation

#226 circuit drawing in documentation
  docs/images/figures/summary_of_quantum_operations_0.png
  docs/images/figures/summary_of_quantum_operations_1.png
  docs/images/figures/summary_of_quantum_operations_10.png
  docs/images/figures/summary_of_quantum_operations_11.png
  docs/images/figures/summary_of_quantum_operations_12.png
  docs/images/figures/summary_of_quantum_operations_13.png
  docs/images/figures/summary_of_quantum_operations_14.png
  docs/images/figures/summary_of_quantum_operations_15.png
  docs/images/figures/summary_of_quantum_operations_16.png
  docs/images/figures/summary_of_quantum_operations_17.png
  docs/images/figures/summary_of_quantum_operations_18.png
  docs/images/figures/summary_of_quantum_operations_19.png
  docs/images/figures/summary_of_quantum_operations_2.png
  docs/images/figures/summary_of_quantum_operations_20.png
  docs/images/figures/summary_of_quantum_operations_21.png
  docs/images/figures/summary_of_quantum_operations_22.png
  docs/images/figures/summary_of_quantum_operations_23.png
  docs/images/figures/summary_of_quantum_operations_24.png
  docs/images/figures/summary_of_quantum_operations_25.png
  docs/images/figures/summary_of_quantum_operations_26.png
  docs/images/figures/summary_of_quantum_operations_27.png
  docs/images/figures/summary_of_quantum_operations_28.png
  docs/images/figures/summary_of_quantum_operations_29.png
  docs/images/figures/summary_of_quantum_operations_3.png
  docs/images/figures/summary_of_quantum_operations_30.png
  docs/images/figures/summary_of_quantum_operations_31.png
  docs/images/figures/summary_of_quantum_operations_4.png
  docs/images/figures/summary_of_quantum_operations_5.png
  docs/images/figures/summary_of_quantum_operations_6.png
  docs/images/figures/summary_of_quantum_operations_7.png
  docs/images/figures/summary_of_quantum_operations_8.png
  docs/images/figures/summary_of_quantum_operations_9.png
  docs/terra/summary_of_quantum_operations.rst
Labels: documentation

#221 update Release History
  docs/conf.py
  docs/release_history.rst
Labels: documentation

#188 Update optimizers.rst
  docs/aqua/algorithms.rst
  docs/aqua/neural_networks.rst
  docs/aqua/optimizers.rst
Labels: documentation

#247 update Install for Qiskit 0.9
  docs/install.rst
Labels: documentation

#248 update Getting Started for Qiskit 0.9
  docs/getting_started.rst
Labels: documentation

#258 Update tutorials broken link
  docs/theme/_templates/layout.html
Labels: bug

#257 merge release notes and make coherent
  docs/conf.py
  docs/index.rst
  docs/release_notes.rst
Labels: documentation

#262 fixes various typos in Release History
  docs/release_notes.rst
Labels: documentation

#267 document Terra 0.8 circuit API updates
  docs/images/figures/custom_gates_0.png
  docs/images/figures/custom_gates_1.png
  docs/images/figures/custom_gates_2.png
  docs/images/figures/custom_gates_3.png
  docs/images/figures/custom_gates_4.png
  docs/images/figures/custom_gates_5.png
  docs/images/figures/custom_gates_6.png
  docs/images/figures/custom_gates_7.png
  docs/images/figures/custom_gates_8.png
  docs/images/figures/quantum_circuits_3.png
  docs/images/figures/quantum_circuits_4.png
  docs/terra/custom_gates.rst
  docs/terra/index.rst
  docs/terra/quantum_circuits.rst
  docs/terra/summary_of_quantum_operations.rst
Labels: documentation

#269 added segment analytics code
  docs/theme/_templates/layout.html
Labels: enhancement

#275 add transpiler to doc
  docs/images/figures/transpiler_api_overview_0.png
  docs/images/figures/transpiler_api_overview_1.png
  docs/terra/index.rst
  docs/terra/transpiler/about/api.rst
  docs/terra/transpiler/about/index.rst
  docs/terra/transpiler/about/pass_managers.rst
  docs/terra/transpiler/about/passes.rst
  docs/terra/transpiler/getting_started.rst
  docs/terra/transpiler/index.rst
Labels: documentation

#279 hone getting started
  docs/faq.rst
  docs/getting_started.rst
  docs/images/figures/executing_quantum_programs_0.png
  docs/images/figures/executing_quantum_programs_1.png
  docs/images/figures/executing_quantum_programs_2.png
  docs/images/figures/executing_quantum_programs_3.png
  docs/images/figures/executing_quantum_programs_4.png
  docs/images/figures/executing_quantum_programs_5.png
  docs/images/figures/getting_started_14_0.png
  docs/images/figures/getting_started_1_1.png
  docs/images/figures/getting_started_2_0.png
  docs/terra/executing_quantum_programs.rst
  docs/terra/index.rst
  docs/terra/plotting_data_in_qiskit.rst
  docs/terra/visualizing_a_quantum_circuit.rst
Labels: documentation

#284 Bugfix analytics: Added more options to track
  docs/theme/_templates/layout.html
Labels: bug

#286 add style guide, clarify instructions for building doc locally
  docs/contributing_to_qiskit.rst
Labels: documentation

#295 update install instructions
  docs/images/figures/install_api_token.png
  docs/images/figures/install_copy_url.png
  docs/images/figures/install_my_account.png
  docs/install.rst
Labels: documentation
