Repository Qiskit/qiskit-metapackage, pull requests merged in 2019-09, with the labels that each got.

#525 give Crowdin credit
  docs/contributing_to_qiskit.rst
Labels: Localization

#527 Update LOCALIZATION_CONTRIBUTORS
  docs/LOCALIZATION_CONTRIBUTORS
Labels: Localization

#526 Update Localization contributor to include ibmamnt
  docs/LOCALIZATION_CONTRIBUTORS
Labels: Localization

#543 Fix/toggle button
  docs/theme/_templates/globaltoc.html
  docs/theme/static/css/theme.css
Labels: Localization, documentation

#566 Changed the lang for sphinx make gettext
  tools/deploy_documentation.sh
Labels: Localization

#578 Corrected IBM Q Account redirection link
  docs/theme/_templates/layout.html
Labels: bug

#580 Adding new user request for Spanish translation.
  docs/LOCALIZATION_CONTRIBUTORS
Labels: Localization, documentation

#587 Update LOCALIZATION_CONTRIBUTORS
  docs/LOCALIZATION_CONTRIBUTORS
Labels: Localization, documentation

#590 Remove .po files of api/ and apidoc/ from poBranch
  tools/deploy_documentation.sh
Labels: Localization, documentation

#591 Added conf to remove _sources
  docs/conf.py
Labels: documentation

#594 more legally sound wording
  docs/contributing_to_qiskit.rst
Labels: documentation
