Repository Qiskit/qiskit-metapackage, pull requests merged in 2022-12, with the labels that each got.

#1631 Update repo to use new qiskit sphinx theme
  .github/workflows/docs.yml
  docs/_templates/layout.html
  docs/conf.py
  docs/index.rst
  requirements-dev.txt
Labels: documentation

#1635 Fix analytics environment in deployment
  tox.ini
Labels: documentation, automerge

#1645 warning box in README that Aer and IBMQ provider will be removed
  README.md
Labels: automerge
